package com.whatdy.model;

public class ProxyIp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_ip.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_ip.port
     *
     * @mbg.generated
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_ip.speed
     *
     * @mbg.generated
     */
    private Float speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_ip.proxy_type
     *
     * @mbg.generated
     */
    private String proxyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_ip.available
     *
     * @mbg.generated
     */
    private String available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_ip.ip
     *
     * @return the value of proxy_ip.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_ip.ip
     *
     * @param ip the value for proxy_ip.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_ip.port
     *
     * @return the value of proxy_ip.port
     *
     * @mbg.generated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_ip.port
     *
     * @param port the value for proxy_ip.port
     *
     * @mbg.generated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_ip.speed
     *
     * @return the value of proxy_ip.speed
     *
     * @mbg.generated
     */
    public Float getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_ip.speed
     *
     * @param speed the value for proxy_ip.speed
     *
     * @mbg.generated
     */
    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_ip.proxy_type
     *
     * @return the value of proxy_ip.proxy_type
     *
     * @mbg.generated
     */
    public String getProxyType() {
        return proxyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_ip.proxy_type
     *
     * @param proxyType the value for proxy_ip.proxy_type
     *
     * @mbg.generated
     */
    public void setProxyType(String proxyType) {
        this.proxyType = proxyType == null ? null : proxyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_ip.available
     *
     * @return the value of proxy_ip.available
     *
     * @mbg.generated
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_ip.available
     *
     * @param available the value for proxy_ip.available
     *
     * @mbg.generated
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }
}