package com.whatdy.mapper;

import com.whatdy.model.ProxyIp;
import java.util.List;

public interface ProxyIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_ip
     *
     * @mbg.generated
     */
    int insert(ProxyIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_ip
     *
     * @mbg.generated
     */
    List<ProxyIp> selectAll();
}